apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: helm-falco
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1"
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: Installs the Falco Helm chart for runtime security and threat detection.
  license: Apache-2.0
  maintainer: Patrick Lee Scott <pat@patscott.io>
  readme: |
    # helm-falco

    Installs the Falco Helm chart using Crossplane and the Helm provider.
    Falco is a CNCF graduated project for cloud-native runtime security.
  repository: ghcr.io/hops-ops/helm-falco
  source: github.com/hops-ops/helm-falco
